# Generated by Django 6.0.1 on 2026-01-10 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_priceobservation_promotion_purchasedocument_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="alertrule",
            options={
                "verbose_name": "Regla de Alerta",
                "verbose_name_plural": "Reglas de Alerta",
            },
        ),
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "verbose_name": "Log de Auditoría",
                "verbose_name_plural": "Logs de Auditoría",
            },
        ),
        migrations.AlterModelOptions(
            name="banner",
            options={
                "verbose_name": "Banner / Formato",
                "verbose_name_plural": "Banners / Formatos",
            },
        ),
        migrations.AlterModelOptions(
            name="chain",
            options={"verbose_name": "Cadena", "verbose_name_plural": "Cadenas"},
        ),
        migrations.AlterModelOptions(
            name="client",
            options={"verbose_name": "Cliente", "verbose_name_plural": "Clientes"},
        ),
        migrations.AlterModelOptions(
            name="dataqualityissue",
            options={
                "verbose_name": "Problema de Calidad de Datos",
                "verbose_name_plural": "Problemas de Calidad de Datos",
            },
        ),
        migrations.AlterModelOptions(
            name="datasource",
            options={
                "verbose_name": "Fuente de Datos",
                "verbose_name_plural": "Fuentes de Datos",
            },
        ),
        migrations.AlterModelOptions(
            name="ingestionjobrun",
            options={
                "verbose_name": "Ejecución de Ingesta",
                "verbose_name_plural": "Ejecuciones de Ingesta",
            },
        ),
        migrations.AlterModelOptions(
            name="kpidefinition",
            options={
                "verbose_name": "Definición de KPI",
                "verbose_name_plural": "Definiciones de KPI",
            },
        ),
        migrations.AlterModelOptions(
            name="oosobservation",
            options={
                "verbose_name": "Observación de Quiebre (OOS)",
                "verbose_name_plural": "Observaciones de Quiebre (OOS)",
            },
        ),
        migrations.AlterModelOptions(
            name="pharmacy",
            options={"verbose_name": "Farmacia", "verbose_name_plural": "Farmacias"},
        ),
        migrations.AlterModelOptions(
            name="pharmacycontact",
            options={
                "verbose_name": "Contacto de Farmacia",
                "verbose_name_plural": "Contactos de Farmacia",
            },
        ),
        migrations.AlterModelOptions(
            name="popdeployment",
            options={
                "verbose_name": "Implementación POP",
                "verbose_name_plural": "Implementaciones POP",
            },
        ),
        migrations.AlterModelOptions(
            name="priceobservation",
            options={
                "verbose_name": "Observación de Precio",
                "verbose_name_plural": "Observaciones de Precio",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Producto", "verbose_name_plural": "Productos"},
        ),
        migrations.AlterModelOptions(
            name="productbrand",
            options={"verbose_name": "Marca", "verbose_name_plural": "Marcas"},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={
                "verbose_name": "Categoría de Producto",
                "verbose_name_plural": "Categorías de Producto",
            },
        ),
        migrations.AlterModelOptions(
            name="promotion",
            options={"verbose_name": "Promoción", "verbose_name_plural": "Promociones"},
        ),
        migrations.AlterModelOptions(
            name="purchasedocument",
            options={
                "verbose_name": "Orden de Compra",
                "verbose_name_plural": "Órdenes de Compra",
            },
        ),
        migrations.AlterModelOptions(
            name="purchaseline",
            options={
                "verbose_name": "Línea de Compra",
                "verbose_name_plural": "Líneas de Compra",
            },
        ),
        migrations.AlterModelOptions(
            name="region",
            options={"verbose_name": "Región", "verbose_name_plural": "Regiones"},
        ),
        migrations.AlterModelOptions(
            name="rep",
            options={
                "verbose_name": "Representante",
                "verbose_name_plural": "Representantes",
            },
        ),
        migrations.AlterModelOptions(
            name="salesdocument",
            options={
                "verbose_name": "Documento de Venta",
                "verbose_name_plural": "Documentos de Venta",
            },
        ),
        migrations.AlterModelOptions(
            name="salesline",
            options={
                "verbose_name": "Línea de Venta",
                "verbose_name_plural": "Líneas de Venta",
            },
        ),
        migrations.AlterModelOptions(
            name="shipment",
            options={"verbose_name": "Envío", "verbose_name_plural": "Envíos"},
        ),
        migrations.AlterModelOptions(
            name="stockmovement",
            options={
                "verbose_name": "Movimiento de Stock",
                "verbose_name_plural": "Movimientos de Stock",
            },
        ),
        migrations.AlterModelOptions(
            name="stocksnapshot",
            options={
                "verbose_name": "Snapshot de Stock",
                "verbose_name_plural": "Snapshots de Stock",
            },
        ),
        migrations.AlterModelOptions(
            name="supplier",
            options={"verbose_name": "Proveedor", "verbose_name_plural": "Proveedores"},
        ),
        migrations.AlterModelOptions(
            name="territory",
            options={
                "verbose_name": "Territorio",
                "verbose_name_plural": "Territorios",
            },
        ),
        migrations.AlterModelOptions(
            name="visit",
            options={"verbose_name": "Visita", "verbose_name_plural": "Visitas"},
        ),
        migrations.AlterModelOptions(
            name="visittask",
            options={
                "verbose_name": "Tarea de Visita",
                "verbose_name_plural": "Tareas de Visita",
            },
        ),
        migrations.AlterModelOptions(
            name="zone",
            options={"verbose_name": "Zona", "verbose_name_plural": "Zonas"},
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="emails_to_notify",
            field=models.JSONField(default=list, verbose_name="Emails a Notificar"),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="kpi",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.kpidefinition",
                verbose_name="KPI",
            ),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="threshold_max",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, null=True, verbose_name="Umbral Máximo"
            ),
        ),
        migrations.AlterField(
            model_name="alertrule",
            name="threshold_min",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, null=True, verbose_name="Umbral Mínimo"
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(max_length=50, verbose_name="Acción"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="changes",
            field=models.JSONField(default=dict, verbose_name="Cambios"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="model_name",
            field=models.CharField(max_length=100, verbose_name="Nombre del Modelo"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_id",
            field=models.CharField(max_length=100, verbose_name="ID Objeto"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Fecha/Hora"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="chain",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.chain",
                verbose_name="Cadena",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="banner",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="chain",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="chain",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="client",
            name="config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Configuraciones de KPIs, reglas, umbrales",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="country",
            field=models.CharField(max_length=100, verbose_name="País"),
        ),
        migrations.AlterField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha de Creación"
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="currency",
            field=models.CharField(default="USD", max_length=10, verbose_name="Moneda"),
        ),
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="client",
            name="timezone",
            field=models.CharField(
                default="UTC", max_length=50, verbose_name="Zona Horaria"
            ),
        ),
        migrations.AlterField(
            model_name="dataqualityissue",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="dataqualityissue",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Fecha Creación"
            ),
        ),
        migrations.AlterField(
            model_name="dataqualityissue",
            name="description",
            field=models.TextField(verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="dataqualityissue",
            name="entity",
            field=models.CharField(max_length=100, verbose_name="Entidad"),
        ),
        migrations.AlterField(
            model_name="dataqualityissue",
            name="issue_type",
            field=models.CharField(max_length=50, verbose_name="Tipo de Problema"),
        ),
        migrations.AlterField(
            model_name="dataqualityissue",
            name="resolved",
            field=models.BooleanField(default=False, verbose_name="Resuelto"),
        ),
        migrations.AlterField(
            model_name="dataqualityissue",
            name="severity",
            field=models.CharField(
                choices=[("LOW", "Baja"), ("MEDIUM", "Media"), ("HIGH", "Alta")],
                max_length=10,
                verbose_name="Severidad",
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="config",
            field=models.JSONField(
                default=dict,
                help_text="Credenciales, rutas, vault",
                verbose_name="Configuración",
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="owner",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Responsable"
            ),
        ),
        migrations.AlterField(
            model_name="datasource",
            name="type",
            field=models.CharField(
                choices=[
                    ("DB", "Base de Datos"),
                    ("API", "API"),
                    ("EXCEL", "Excel"),
                    ("SHEETS", "Google Sheets"),
                ],
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="ingestionjobrun",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Hora Fin"),
        ),
        migrations.AlterField(
            model_name="ingestionjobrun",
            name="errors",
            field=models.JSONField(default=list, verbose_name="Errores"),
        ),
        migrations.AlterField(
            model_name="ingestionjobrun",
            name="rows_processed",
            field=models.IntegerField(default=0, verbose_name="Filas Procesadas"),
        ),
        migrations.AlterField(
            model_name="ingestionjobrun",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.datasource",
                verbose_name="Fuente",
            ),
        ),
        migrations.AlterField(
            model_name="ingestionjobrun",
            name="start_time",
            field=models.DateTimeField(verbose_name="Hora Inicio"),
        ),
        migrations.AlterField(
            model_name="ingestionjobrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("RUNNING", "Ejecutando"),
                    ("SUCCESS", "Exitoso"),
                    ("FAILED", "Fallido"),
                ],
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="kpidefinition",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="kpidefinition",
            name="code",
            field=models.CharField(max_length=50, verbose_name="Código"),
        ),
        migrations.AlterField(
            model_name="kpidefinition",
            name="formula",
            field=models.TextField(
                help_text="Descripción del cálculo", verbose_name="Fórmula"
            ),
        ),
        migrations.AlterField(
            model_name="kpidefinition",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="kpidefinition",
            name="target_value",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Valor Objetivo",
            ),
        ),
        migrations.AlterField(
            model_name="oosobservation",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="oosobservation",
            name="date_detected",
            field=models.DateTimeField(verbose_name="Fecha Detección"),
        ),
        migrations.AlterField(
            model_name="oosobservation",
            name="is_confirmed",
            field=models.BooleanField(default=True, verbose_name="Confirmado"),
        ),
        migrations.AlterField(
            model_name="oosobservation",
            name="pharmacy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.pharmacy",
                verbose_name="Farmacia",
            ),
        ),
        migrations.AlterField(
            model_name="oosobservation",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.product",
                verbose_name="Producto",
            ),
        ),
        migrations.AlterField(
            model_name="oosobservation",
            name="source",
            field=models.CharField(max_length=50, verbose_name="Fuente"),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="address",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Dirección"
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="attributes",
            field=models.JSONField(
                default=dict,
                help_text="E-commerce habilitado, detalles de infraestructura",
                verbose_name="Atributos",
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="banner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analytics.banner",
                verbose_name="Banner",
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Ciudad"),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="display_name",
            field=models.CharField(max_length=200, verbose_name="Nombre Visual"),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="external_id",
            field=models.CharField(max_length=100, verbose_name="ID Externo"),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Latitud",
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Longitud",
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="name_legal",
            field=models.CharField(max_length=200, verbose_name="Razón Social"),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="name_trade",
            field=models.CharField(max_length=200, verbose_name="Nombre Fantasía"),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="segments",
            field=models.JSONField(
                default=dict,
                help_text="ABC, estratégica, potencial de crecimiento",
                verbose_name="Segmentos",
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="state",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Provincia/Estado"
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Activa"), ("INACTIVE", "Inactiva")],
                default="ACTIVE",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="territory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analytics.territory",
                verbose_name="Territorio",
            ),
        ),
        migrations.AlterField(
            model_name="pharmacycontact",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="pharmacycontact",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="pharmacycontact",
            name="pharmacy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.pharmacy",
                verbose_name="Farmacia",
            ),
        ),
        migrations.AlterField(
            model_name="pharmacycontact",
            name="phone",
            field=models.CharField(blank=True, max_length=50, verbose_name="Teléfono"),
        ),
        migrations.AlterField(
            model_name="pharmacycontact",
            name="role",
            field=models.CharField(max_length=50, verbose_name="Rol"),
        ),
        migrations.AlterField(
            model_name="popdeployment",
            name="campaign",
            field=models.CharField(blank=True, max_length=100, verbose_name="Campaña"),
        ),
        migrations.AlterField(
            model_name="popdeployment",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="popdeployment",
            name="installed_at",
            field=models.DateTimeField(verbose_name="Fecha Instalación"),
        ),
        migrations.AlterField(
            model_name="popdeployment",
            name="material_type",
            field=models.CharField(max_length=100, verbose_name="Tipo de Material"),
        ),
        migrations.AlterField(
            model_name="popdeployment",
            name="pharmacy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.pharmacy",
                verbose_name="Farmacia",
            ),
        ),
        migrations.AlterField(
            model_name="popdeployment",
            name="photo_url",
            field=models.URLField(blank=True, verbose_name="URL Foto"),
        ),
        migrations.AlterField(
            model_name="priceobservation",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="priceobservation",
            name="date_observed",
            field=models.DateField(verbose_name="Fecha Observación"),
        ),
        migrations.AlterField(
            model_name="priceobservation",
            name="is_promo",
            field=models.BooleanField(default=False, verbose_name="En Promoción"),
        ),
        migrations.AlterField(
            model_name="priceobservation",
            name="pharmacy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.pharmacy",
                verbose_name="Farmacia",
            ),
        ),
        migrations.AlterField(
            model_name="priceobservation",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="Precio Observado"
            ),
        ),
        migrations.AlterField(
            model_name="priceobservation",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.product",
                verbose_name="Producto",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analytics.productbrand",
                verbose_name="Marca",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analytics.productcategory",
                verbose_name="Categoría",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="ean",
            field=models.CharField(blank=True, max_length=100, verbose_name="EAN"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AlterField(
            model_name="product",
            name="is_essential",
            field=models.BooleanField(default=False, verbose_name="Es Esencial/Core"),
        ),
        migrations.AlterField(
            model_name="product",
            name="lifecycle_stage",
            field=models.CharField(
                default="ACTIVE", max_length=50, verbose_name="Ciclo de Vida"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="product",
            name="pack_size",
            field=models.IntegerField(default=1, verbose_name="Tamaño de Pack"),
        ),
        migrations.AlterField(
            model_name="product",
            name="presentation",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Presentación"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=100, verbose_name="SKU"),
        ),
        migrations.AlterField(
            model_name="productbrand",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="productbrand",
            name="laboratory",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Laboratorio"
            ),
        ),
        migrations.AlterField(
            model_name="productbrand",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analytics.productcategory",
                verbose_name="Categoría Padre",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="end_date",
            field=models.DateField(verbose_name="Fecha Fin"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="mechanic",
            field=models.CharField(max_length=100, verbose_name="Mecánica"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nombre Promoción"),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="products",
            field=models.ManyToManyField(
                to="analytics.product", verbose_name="Productos"
            ),
        ),
        migrations.AlterField(
            model_name="promotion",
            name="start_date",
            field=models.DateField(verbose_name="Fecha Inicio"),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="date_ordered",
            field=models.DateField(verbose_name="Fecha Orden"),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="date_received",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha Recepción"
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="external_id",
            field=models.CharField(max_length=100, verbose_name="ID Externo"),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="status",
            field=models.CharField(max_length=50, verbose_name="Estado"),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="supplier",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.supplier",
                verbose_name="Proveedor",
            ),
        ),
        migrations.AlterField(
            model_name="purchasedocument",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Monto Total"
            ),
        ),
        migrations.AlterField(
            model_name="purchaseline",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="analytics.purchasedocument",
                verbose_name="Documento",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.product",
                verbose_name="Producto",
            ),
        ),
        migrations.AlterField(
            model_name="purchaseline",
            name="quantity_ordered",
            field=models.IntegerField(verbose_name="Cant. Pedida"),
        ),
        migrations.AlterField(
            model_name="purchaseline",
            name="quantity_received",
            field=models.IntegerField(default=0, verbose_name="Cant. Recibida"),
        ),
        migrations.AlterField(
            model_name="region",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="region",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analytics.region",
                verbose_name="Región Padre",
            ),
        ),
        migrations.AlterField(
            model_name="rep",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="rep",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="rep",
            name="territory",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analytics.territory",
                verbose_name="Territorio",
            ),
        ),
        migrations.AlterField(
            model_name="rep",
            name="user",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario de Sistema",
            ),
        ),
        migrations.AlterField(
            model_name="salesdocument",
            name="channel",
            field=models.CharField(
                default="OFFLINE", max_length=50, verbose_name="Canal"
            ),
        ),
        migrations.AlterField(
            model_name="salesdocument",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="salesdocument",
            name="currency",
            field=models.CharField(max_length=10, verbose_name="Moneda"),
        ),
        migrations.AlterField(
            model_name="salesdocument",
            name="date",
            field=models.DateTimeField(verbose_name="Fecha"),
        ),
        migrations.AlterField(
            model_name="salesdocument",
            name="doc_type",
            field=models.CharField(max_length=50, verbose_name="Tipo Doc"),
        ),
        migrations.AlterField(
            model_name="salesdocument",
            name="external_id",
            field=models.CharField(max_length=100, verbose_name="ID Externo"),
        ),
        migrations.AlterField(
            model_name="salesdocument",
            name="pharmacy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.pharmacy",
                verbose_name="Farmacia",
            ),
        ),
        migrations.AlterField(
            model_name="salesdocument",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Monto Total"
            ),
        ),
        migrations.AlterField(
            model_name="salesline",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Monto Descuento",
            ),
        ),
        migrations.AlterField(
            model_name="salesline",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="analytics.salesdocument",
                verbose_name="Documento",
            ),
        ),
        migrations.AlterField(
            model_name="salesline",
            name="is_promo",
            field=models.BooleanField(default=False, verbose_name="Es Promoción"),
        ),
        migrations.AlterField(
            model_name="salesline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.product",
                verbose_name="Producto",
            ),
        ),
        migrations.AlterField(
            model_name="salesline",
            name="quantity",
            field=models.IntegerField(verbose_name="Cantidad"),
        ),
        migrations.AlterField(
            model_name="salesline",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Precio Total"
            ),
        ),
        migrations.AlterField(
            model_name="salesline",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Precio Unitario"
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="delivered_at",
            field=models.DateTimeField(null=True, verbose_name="Fecha Entrega"),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="destination_pharmacy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.pharmacy",
                verbose_name="Farmacia Destino",
            ),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="dispatched_at",
            field=models.DateTimeField(verbose_name="Fecha Despacho"),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="origin",
            field=models.CharField(max_length=100, verbose_name="Origen"),
        ),
        migrations.AlterField(
            model_name="shipment",
            name="status",
            field=models.CharField(max_length=50, verbose_name="Estado"),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="date",
            field=models.DateTimeField(verbose_name="Fecha"),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="pharmacy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.pharmacy",
                verbose_name="Farmacia",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.product",
                verbose_name="Producto",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="quantity",
            field=models.IntegerField(verbose_name="Cantidad"),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="reason",
            field=models.CharField(blank=True, max_length=100, verbose_name="Motivo"),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="type",
            field=models.CharField(
                choices=[("IN", "Entrada"), ("OUT", "Salida"), ("ADJUST", "Ajuste")],
                max_length=20,
                verbose_name="Tipo",
            ),
        ),
        migrations.AlterField(
            model_name="stocksnapshot",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="stocksnapshot",
            name="date",
            field=models.DateField(verbose_name="Fecha"),
        ),
        migrations.AlterField(
            model_name="stocksnapshot",
            name="pharmacy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.pharmacy",
                verbose_name="Farmacia",
            ),
        ),
        migrations.AlterField(
            model_name="stocksnapshot",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.product",
                verbose_name="Producto",
            ),
        ),
        migrations.AlterField(
            model_name="stocksnapshot",
            name="quantity_in_transit",
            field=models.IntegerField(default=0, verbose_name="Cant. en Tránsito"),
        ),
        migrations.AlterField(
            model_name="stocksnapshot",
            name="quantity_on_hand",
            field=models.IntegerField(verbose_name="Cant. Disponible"),
        ),
        migrations.AlterField(
            model_name="stocksnapshot",
            name="quantity_reserved",
            field=models.IntegerField(default=0, verbose_name="Cant. Reservada"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="supplier",
            name="type",
            field=models.CharField(max_length=50, verbose_name="Tipo"),
        ),
        migrations.AlterField(
            model_name="territory",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="territory",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="territory",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.zone",
                verbose_name="Zona",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="check_in",
            field=models.DateTimeField(verbose_name="Check-in"),
        ),
        migrations.AlterField(
            model_name="visit",
            name="check_out",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Check-out"),
        ),
        migrations.AlterField(
            model_name="visit",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="duration_minutes",
            field=models.IntegerField(default=0, verbose_name="Duración (min)"),
        ),
        migrations.AlterField(
            model_name="visit",
            name="is_valid_location",
            field=models.BooleanField(default=True, verbose_name="Ubicación Válida"),
        ),
        migrations.AlterField(
            model_name="visit",
            name="latitude_check_in",
            field=models.DecimalField(
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Latitud Check-in",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="longitude_check_in",
            field=models.DecimalField(
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Longitud Check-in",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="outcome",
            field=models.JSONField(
                default=dict,
                help_text="Resultado, Pedido generado, etc",
                verbose_name="Resultado",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="pharmacy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.pharmacy",
                verbose_name="Farmacia",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="rep",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.rep",
                verbose_name="Representante",
            ),
        ),
        migrations.AlterField(
            model_name="visittask",
            name="is_compliant",
            field=models.BooleanField(default=True, verbose_name="Cumple"),
        ),
        migrations.AlterField(
            model_name="visittask",
            name="question",
            field=models.CharField(max_length=255, verbose_name="Pregunta/Tarea"),
        ),
        migrations.AlterField(
            model_name="visittask",
            name="response",
            field=models.JSONField(default=dict, verbose_name="Respuesta"),
        ),
        migrations.AlterField(
            model_name="visittask",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to="analytics.visit",
                verbose_name="Visita",
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.client",
                verbose_name="Cliente",
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="zone",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.region",
                verbose_name="Región",
            ),
        ),
    ]
