# Generated by Django 6.0.1 on 2026-01-10 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_alter_alertrule_options_alter_auditlog_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesdocument",
            name="coupon_code",
            field=models.CharField(blank=True, max_length=50, verbose_name="Cupón"),
        ),
        migrations.AddField(
            model_name="salesdocument",
            name="order_source",
            field=models.CharField(
                blank=True,
                help_text="Web, App, Call Center",
                max_length=100,
                verbose_name="Origen Pedido",
            ),
        ),
        migrations.AddField(
            model_name="salesdocument",
            name="status",
            field=models.CharField(
                default="COMPLETED", max_length=50, verbose_name="Estado"
            ),
        ),
        migrations.AddField(
            model_name="salesline",
            name="combo_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="Combo"),
        ),
        migrations.AddField(
            model_name="salesline",
            name="discount_coupon_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=12, verbose_name="Desc. Cupón"
            ),
        ),
        migrations.AddField(
            model_name="salesline",
            name="return_status",
            field=models.CharField(
                choices=[
                    ("DELIVERED", "Entregado"),
                    ("REJECTED", "Rechazado"),
                    ("MISSING", "Faltante"),
                ],
                default="DELIVERED",
                max_length=20,
                verbose_name="Estado Retorno",
            ),
        ),
    ]
