# Generated by Django 6.0 on 2026-01-11 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics",
            "0004_salesdocument_coupon_code_salesdocument_order_source_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="client",
            options={
                "permissions": [
                    ("view_dashboard", "Can view dashboard"),
                    ("view_visits", "Can view visits"),
                    ("view_routes", "Can view optimized routes"),
                ],
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
            },
        ),
    ]
