# Generated by Django 6.0 on 2026-01-11 03:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0005_alter_client_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Catalog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="CatalogOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("label", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "label"],
            },
        ),
        migrations.CreateModel(
            name="EvidenceFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="evidence/%Y/%m/%d/")),
                ("file_type", models.CharField(default="PHOTO", max_length=20)),
                (
                    "latitude",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="FormAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value_text", models.TextField(blank=True, null=True)),
                ("value_int", models.IntegerField(blank=True, null=True)),
                (
                    "value_decimal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("value_bool", models.BooleanField(blank=True, null=True)),
                ("value_date", models.DateField(blank=True, null=True)),
                (
                    "raw_value",
                    models.TextField(
                        blank=True, help_text="String representation for quick display"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50)),
                ("version", models.IntegerField(default=1)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=False)),
                ("allow_photos", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FormFieldDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Texto Libre"),
                            ("INT", "Número Entero"),
                            ("DECIMAL", "Decimal"),
                            ("BOOL", "Sí/No"),
                            ("DATE", "Fecha"),
                            ("SELECT", "Selección Única"),
                            ("MULTI_SELECT", "Selección Múltiple"),
                            ("PHOTO", "Foto"),
                            ("SECTION_HEADER", "Encabezado de Sección"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=300)),
                (
                    "code",
                    models.CharField(
                        help_text="Internal slug for reporting", max_length=50
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("help_text", models.CharField(blank=True, max_length=200)),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("conditions", models.JSONField(blank=True, default=list)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("is_valid", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="PopPlacement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PopType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="StockoutObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_oos",
                    models.BooleanField(default=False, verbose_name="Is Out of Stock"),
                ),
                ("cluster_source", models.CharField(default="VISIT", max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name="alertrule",
            name="client",
        ),
        migrations.RemoveField(
            model_name="alertrule",
            name="kpi",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="chain",
        ),
        migrations.RemoveField(
            model_name="banner",
            name="client",
        ),
        migrations.RemoveField(
            model_name="chain",
            name="client",
        ),
        migrations.RemoveField(
            model_name="dataqualityissue",
            name="client",
        ),
        migrations.RemoveField(
            model_name="datasource",
            name="client",
        ),
        migrations.RemoveField(
            model_name="ingestionjobrun",
            name="source",
        ),
        migrations.RemoveField(
            model_name="kpidefinition",
            name="client",
        ),
        migrations.RemoveField(
            model_name="oosobservation",
            name="client",
        ),
        migrations.RemoveField(
            model_name="oosobservation",
            name="pharmacy",
        ),
        migrations.RemoveField(
            model_name="oosobservation",
            name="product",
        ),
        migrations.RemoveField(
            model_name="pharmacycontact",
            name="pharmacy",
        ),
        migrations.RemoveField(
            model_name="popdeployment",
            name="client",
        ),
        migrations.RemoveField(
            model_name="popdeployment",
            name="pharmacy",
        ),
        migrations.RemoveField(
            model_name="priceobservation",
            name="client",
        ),
        migrations.RemoveField(
            model_name="priceobservation",
            name="pharmacy",
        ),
        migrations.RemoveField(
            model_name="priceobservation",
            name="product",
        ),
        migrations.RemoveField(
            model_name="promotion",
            name="client",
        ),
        migrations.RemoveField(
            model_name="promotion",
            name="products",
        ),
        migrations.RemoveField(
            model_name="purchasedocument",
            name="client",
        ),
        migrations.RemoveField(
            model_name="purchasedocument",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="purchaseline",
            name="document",
        ),
        migrations.RemoveField(
            model_name="purchaseline",
            name="product",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="client",
        ),
        migrations.RemoveField(
            model_name="shipment",
            name="destination_pharmacy",
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="client",
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="pharmacy",
        ),
        migrations.RemoveField(
            model_name="stockmovement",
            name="product",
        ),
        migrations.AlterUniqueTogether(
            name="stocksnapshot",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="stocksnapshot",
            name="client",
        ),
        migrations.RemoveField(
            model_name="stocksnapshot",
            name="pharmacy",
        ),
        migrations.RemoveField(
            model_name="stocksnapshot",
            name="product",
        ),
        migrations.RemoveField(
            model_name="supplier",
            name="client",
        ),
        migrations.RemoveField(
            model_name="visittask",
            name="visit",
        ),
        migrations.AlterModelOptions(
            name="auditlog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.AlterModelOptions(
            name="pharmacy",
            options={
                "verbose_name": "Farmacia (PDV)",
                "verbose_name_plural": "Farmacias",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
            },
        ),
        migrations.AlterModelOptions(
            name="productbrand",
            options={"verbose_name": "Marca"},
        ),
        migrations.AlterModelOptions(
            name="productcategory",
            options={"verbose_name": "Categoría de Producto"},
        ),
        migrations.AlterModelOptions(
            name="region",
            options={"verbose_name": "Región"},
        ),
        migrations.AlterModelOptions(
            name="rep",
            options={
                "verbose_name": "Visitador (Rep)",
                "verbose_name_plural": "Visitadores",
            },
        ),
        migrations.AlterModelOptions(
            name="salesdocument",
            options={},
        ),
        migrations.AlterModelOptions(
            name="salesline",
            options={},
        ),
        migrations.AlterModelOptions(
            name="territory",
            options={"verbose_name": "Territorio"},
        ),
        migrations.AlterModelOptions(
            name="visit",
            options={"ordering": ["-started_at"]},
        ),
        migrations.AlterModelOptions(
            name="zone",
            options={"verbose_name": "Zona"},
        ),
        migrations.RemoveField(
            model_name="client",
            name="config",
        ),
        migrations.RemoveField(
            model_name="client",
            name="country",
        ),
        migrations.RemoveField(
            model_name="client",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="client",
            name="timezone",
        ),

        migrations.RemoveField(
            model_name="product",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_essential",
        ),
        migrations.RemoveField(
            model_name="product",
            name="lifecycle_stage",
        ),
        migrations.RemoveField(
            model_name="product",
            name="pack_size",
        ),
        migrations.RemoveField(
            model_name="product",
            name="presentation",
        ),
        migrations.RemoveField(
            model_name="productbrand",
            name="laboratory",
        ),
        migrations.RemoveField(
            model_name="region",
            name="parent",
        ),

        migrations.RemoveField(
            model_name="visit",
            name="check_in",
        ),
        migrations.RemoveField(
            model_name="visit",
            name="check_out",
        ),
        migrations.RemoveField(
            model_name="visit",
            name="duration_minutes",
        ),
        migrations.RemoveField(
            model_name="visit",
            name="is_valid_location",
        ),
        migrations.RemoveField(
            model_name="visit",
            name="outcome",
        ),
        migrations.AddField(
            model_name="client",
            name="code",
            field=models.CharField(
                default="default_code",
                max_length=50,

                verbose_name="Código",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="client",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="code",
            field=models.CharField(
                default="default_pharmacy",
                help_text="Código único en el sistema del cliente",
                max_length=50,
                verbose_name="Código Interno",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="segment_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Tags, Cluster, Segmento"
            ),
        ),
        migrations.AddField(
            model_name="pharmacy",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20, verbose_name="CP"),
        ),
        migrations.AddField(
            model_name="rep",
            name="external_id",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="ID Legajo/Externo"
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visit",
            name="distance_from_target",
            field=models.IntegerField(
                help_text="Meters from pharmacy location", null=True
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="scheduled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="visit",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Borrador"),
                    ("SUBMITTED", "Enviado"),
                    ("VALIDATED", "Validado"),
                    ("REJECTED", "Rechazado"),
                ],
                default="DRAFT",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="changes",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="model_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="client",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="address",
            field=models.CharField(max_length=255, verbose_name="Dirección"),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="city",
            field=models.CharField(max_length=100, verbose_name="Ciudad"),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analytics.client"
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="external_id",
            field=models.CharField(
                blank=True,
                help_text="ID en sistema origen/ERP",
                max_length=100,
                verbose_name="ID Externo",
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="state",
            field=models.CharField(max_length=100, verbose_name="Provincia"),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="territory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analytics.territory",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analytics.productbrand",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analytics.productcategory",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analytics.client"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="ean",
            field=models.CharField(blank=True, max_length=50, verbose_name="EAN"),
        ),
        migrations.AlterField(
            model_name="product",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sku",
            field=models.CharField(max_length=50, verbose_name="SKU"),
        ),
        migrations.AlterField(
            model_name="productbrand",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analytics.client"
            ),
        ),
        migrations.AlterField(
            model_name="productbrand",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="productbrand",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analytics.client"
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analytics.productcategory",
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analytics.client"
            ),
        ),
        migrations.AlterField(
            model_name="region",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="rep",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analytics.client"
            ),
        ),
        migrations.AlterField(
            model_name="rep",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="rep",
            name="territory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analytics.territory",
            ),
        ),
        migrations.AlterField(
            model_name="rep",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rep_profile",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="salesdocument",
            name="channel",
            field=models.CharField(default="OFFLINE", max_length=50),
        ),
        migrations.AlterField(
            model_name="salesdocument",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analytics.client"
            ),
        ),
        migrations.AlterField(
            model_name="salesdocument",
            name="coupon_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="salesdocument",
            name="currency",
            field=models.CharField(default="USD", max_length=10),
        ),
        migrations.AlterField(
            model_name="salesdocument",
            name="date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="salesdocument",
            name="doc_type",
            field=models.CharField(default="TICKET", max_length=50),
        ),
        migrations.AlterField(
            model_name="salesdocument",
            name="external_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="salesdocument",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="salesdocument",
            name="order_source",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="salesdocument",
            name="pharmacy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analytics.pharmacy"
            ),
        ),
        migrations.AlterField(
            model_name="salesdocument",
            name="status",
            field=models.CharField(default="COMPLETED", max_length=50),
        ),
        migrations.AlterField(
            model_name="salesdocument",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="salesline",
            name="combo_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name="salesline",
            name="discount_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="salesline",
            name="discount_coupon_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="salesline",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="analytics.salesdocument",
            ),
        ),
        migrations.AlterField(
            model_name="salesline",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="salesline",
            name="is_promo",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="salesline",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analytics.product"
            ),
        ),
        migrations.AlterField(
            model_name="salesline",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="salesline",
            name="return_status",
            field=models.CharField(
                choices=[
                    ("DELIVERED", "Entregado"),
                    ("REJECTED", "Rechazado"),
                    ("MISSING", "Faltante"),
                ],
                default="DELIVERED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="salesline",
            name="total_price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="salesline",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="territory",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analytics.client"
            ),
        ),
        migrations.AlterField(
            model_name="territory",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="territory",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analytics.zone"
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analytics.client"
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="latitude_check_in",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="longitude_check_in",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="pharmacy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analytics.pharmacy"
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="rep",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analytics.rep"
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analytics.client"
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="analytics.region",
            ),
        ),
        migrations.AddIndex(
            model_name="pharmacy",
            index=models.Index(
                fields=["client", "code"], name="analytics_p_client__071db6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pharmacy",
            index=models.Index(
                fields=["client", "city"], name="analytics_p_client__e9b9c1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["client", "rep", "started_at"],
                name="analytics_v_client__de3bca_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["client", "pharmacy"], name="analytics_v_client__0903ba_idx"
            ),
        ),
        migrations.AddField(
            model_name="catalog",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analytics.client"
            ),
        ),
        migrations.AddField(
            model_name="catalogoption",
            name="catalog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="analytics.catalog",
            ),
        ),
        migrations.AddField(
            model_name="formanswer",
            name="value_catalog_options",
            field=models.ManyToManyField(blank=True, to="analytics.catalogoption"),
        ),
        migrations.AddField(
            model_name="evidencefile",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="photos",
                to="analytics.formanswer",
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analytics.client"
            ),
        ),
        migrations.AddField(
            model_name="formfielddefinition",
            name="catalog",
            field=models.ForeignKey(
                blank=True,
                help_text="For select fields",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analytics.catalog",
            ),
        ),
        migrations.AddField(
            model_name="formfielddefinition",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fields",
                to="analytics.formdefinition",
            ),
        ),
        migrations.AddField(
            model_name="formanswer",
            name="field_definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="analytics.formfielddefinition",
            ),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="form_definition",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="analytics.formdefinition",
            ),
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="analytics.visit",
            ),
        ),
        migrations.AddField(
            model_name="formanswer",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answers",
                to="analytics.formsubmission",
            ),
        ),
        migrations.AddField(
            model_name="evidencefile",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence",
                to="analytics.formsubmission",
            ),
        ),
        migrations.AddField(
            model_name="popplacement",
            name="photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="analytics.evidencefile",
            ),
        ),
        migrations.AddField(
            model_name="popplacement",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pop_placements",
                to="analytics.visit",
            ),
        ),
        migrations.AddField(
            model_name="poptype",
            name="client",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="analytics.client"
            ),
        ),
        migrations.AddField(
            model_name="popplacement",
            name="pop_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="analytics.poptype"
            ),
        ),
        migrations.AddField(
            model_name="stockoutobservation",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="analytics.product"
            ),
        ),
        migrations.AddField(
            model_name="stockoutobservation",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stockouts",
                to="analytics.visit",
            ),
        ),
        migrations.DeleteModel(
            name="AlertRule",
        ),
        migrations.DeleteModel(
            name="Chain",
        ),
        migrations.DeleteModel(
            name="DataQualityIssue",
        ),
        migrations.DeleteModel(
            name="DataSource",
        ),
        migrations.DeleteModel(
            name="IngestionJobRun",
        ),
        migrations.DeleteModel(
            name="KPIDefinition",
        ),
        migrations.DeleteModel(
            name="OOSObservation",
        ),
        migrations.DeleteModel(
            name="PharmacyContact",
        ),
        migrations.DeleteModel(
            name="POPDeployment",
        ),
        migrations.DeleteModel(
            name="PriceObservation",
        ),
        migrations.DeleteModel(
            name="Promotion",
        ),
        migrations.DeleteModel(
            name="PurchaseDocument",
        ),
        migrations.DeleteModel(
            name="PurchaseLine",
        ),
        migrations.DeleteModel(
            name="Shipment",
        ),
        migrations.DeleteModel(
            name="StockMovement",
        ),
        migrations.DeleteModel(
            name="StockSnapshot",
        ),
        migrations.DeleteModel(
            name="Supplier",
        ),
        migrations.DeleteModel(
            name="VisitTask",
        ),
        migrations.RemoveField(
            model_name="pharmacy",
            name="attributes",
        ),
        migrations.RemoveField(
            model_name="pharmacy",
            name="banner",
        ),
        migrations.RemoveField(
            model_name="pharmacy",
            name="segments",
        ),
        migrations.RemoveField(
            model_name="pharmacy",
            name="status",
        ),
        migrations.RemoveField(
            model_name="rep",
            name="name",
        ),
        migrations.AlterUniqueTogether(
            name="catalog",
            unique_together={("client", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="formdefinition",
            unique_together={("client", "code", "version")},
        ),
        migrations.AlterUniqueTogether(
            name="formfielddefinition",
            unique_together={("form", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="formsubmission",
            unique_together={("visit", "form_definition")},
        ),
        migrations.AlterUniqueTogether(
            name="formanswer",
            unique_together={("submission", "field_definition")},
        ),
        migrations.AlterUniqueTogether(
            name="poptype",
            unique_together={("client", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="popplacement",
            unique_together={("visit", "pop_type")},
        ),
        migrations.AddIndex(
            model_name="stockoutobservation",
            index=models.Index(
                fields=["visit", "product", "is_oos"],
                name="analytics_s_visit_i_7efd58_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stockoutobservation",
            unique_together={("visit", "product")},
        ),
        migrations.DeleteModel(
            name="Banner",
        ),

    ]
