# Generated by Django 6.0 on 2026-01-13 13:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "analytics",
            "0007_alter_catalog_unique_together_remove_catalog_client_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CommercialAgreement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha Inicio")),
                ("end_date", models.DateField(verbose_name="Fecha Fin")),
                (
                    "description",
                    models.TextField(
                        help_text="Condiciones, beneficios y productos acordados",
                        verbose_name="Descripción / Términos",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.client",
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreements",
                        to="analytics.pharmacy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Acuerdo Comercial",
                "verbose_name_plural": "Acuerdos Comerciales",
                "ordering": ["-start_date"],
            },
        ),
    ]
