# Generated by Django 6.0 on 2026-01-12 17:58

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "analytics",
            "0007_alter_catalog_unique_together_remove_catalog_client_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Catalog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.client",
                    ),
                ),
            ],
            options={
                "unique_together": {("client", "code")},
            },
        ),
        migrations.CreateModel(
            name="CatalogOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("label", models.CharField(max_length=200)),
                ("order", models.IntegerField(default=0)),
                (
                    "catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="surveys.catalog",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "label"],
            },
        ),
        migrations.CreateModel(
            name="FormDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("code", models.CharField(max_length=50)),
                ("version", models.IntegerField(default=1)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=False)),
                ("allow_photos", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.client",
                    ),
                ),
            ],
            options={
                "unique_together": {("client", "code", "version")},
            },
        ),
        migrations.CreateModel(
            name="FormFieldDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Texto Libre"),
                            ("INT", "Número Entero"),
                            ("DECIMAL", "Decimal"),
                            ("BOOL", "Sí/No"),
                            ("DATE", "Fecha"),
                            ("SELECT", "Selección Única"),
                            ("MULTI_SELECT", "Selección Múltiple"),
                            ("PHOTO", "Foto"),
                            ("SECTION_HEADER", "Encabezado de Sección"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(max_length=300)),
                (
                    "code",
                    models.CharField(
                        help_text="Internal slug for reporting", max_length=50
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("help_text", models.CharField(blank=True, max_length=200)),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("conditions", models.JSONField(blank=True, default=list)),
                (
                    "catalog",
                    models.ForeignKey(
                        blank=True,
                        help_text="For select fields",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="surveys.catalog",
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="surveys.formdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
                "unique_together": {("form", "code")},
            },
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("is_valid", models.BooleanField(default=True)),
                (
                    "form_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="surveys.formdefinition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FormAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value_text", models.TextField(blank=True, null=True)),
                ("value_int", models.IntegerField(blank=True, null=True)),
                (
                    "value_decimal",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("value_bool", models.BooleanField(blank=True, null=True)),
                ("value_date", models.DateField(blank=True, null=True)),
                (
                    "raw_value",
                    models.TextField(
                        blank=True, help_text="String representation for quick display"
                    ),
                ),
                (
                    "value_catalog_options",
                    models.ManyToManyField(blank=True, to="surveys.catalogoption"),
                ),
                (
                    "field_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="surveys.formfielddefinition",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="surveys.formsubmission",
                    ),
                ),
            ],
            options={
                "unique_together": {("submission", "field_definition")},
            },
        ),
        migrations.CreateModel(
            name="EvidenceFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.FileField(upload_to="evidence/%Y/%m/%d/")),
                ("file_type", models.CharField(default="PHOTO", max_length=20)),
                (
                    "latitude",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "answer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="photos",
                        to="surveys.formanswer",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence",
                        to="surveys.formsubmission",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PopType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=50)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.client",
                    ),
                ),
            ],
            options={
                "unique_together": {("client", "code")},
            },
        ),
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Borrador"),
                            ("SUBMITTED", "Enviado"),
                            ("VALIDATED", "Validado"),
                            ("REJECTED", "Rechazado"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "latitude_check_in",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude_check_in",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "distance_from_target",
                    models.IntegerField(
                        help_text="Meters from pharmacy location", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.client",
                    ),
                ),
                (
                    "pharmacy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="analytics.pharmacy",
                    ),
                ),
                (
                    "rep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="analytics.rep"
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="StockoutObservation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "is_oos",
                    models.BooleanField(default=False, verbose_name="Is Out of Stock"),
                ),
                ("cluster_source", models.CharField(default="VISIT", max_length=50)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="analytics.product",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stockouts",
                        to="surveys.visit",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PopPlacement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "photo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="surveys.evidencefile",
                    ),
                ),
                (
                    "pop_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="surveys.poptype",
                    ),
                ),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pop_placements",
                        to="surveys.visit",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="formsubmission",
            name="visit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissions",
                to="surveys.visit",
            ),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["client", "rep", "started_at"],
                name="surveys_vis_client__df1bcf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="visit",
            index=models.Index(
                fields=["client", "pharmacy"], name="surveys_vis_client__b67a7a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockoutobservation",
            index=models.Index(
                fields=["visit", "product", "is_oos"],
                name="surveys_sto_visit_i_fe1d8b_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="stockoutobservation",
            unique_together={("visit", "product")},
        ),
        migrations.AlterUniqueTogether(
            name="popplacement",
            unique_together={("visit", "pop_type")},
        ),
        migrations.AlterUniqueTogether(
            name="formsubmission",
            unique_together={("visit", "form_definition")},
        ),
    ]
